name: End-to-end tests
on:
  pull_request:
    branches:
      - "**"
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Change directory to Nuxt-Frontend and install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: cd Nuxt-Frontend && pnpm install

      - name: Cypress run
        run: cd Nuxt-Frontend && pnpm exec cypress run

      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: cypress-screenshots
          path: Nuxt-Frontend/cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: Nuxt-Frontend/cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
          